#buildspec.yml
version: 0.2
phases:
	install:
		pre_build:
			-echo "Pre-build phase - Nothing to do here"
		build:
			-echo "Build phase - Copying website files to S3 bucket"
			-aws s3 sync . s3://$my-little-bucket-pk1 --deletw --acl public-read
		post_build:
			-echo "Post-build phase - Deployment complete!"
	artifacts:
		 -'**/*'
